<Project Sdk="Godot.NET.Sdk/4.8.0-dev.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <None Include="defs\**\*" />
  </ItemGroup>
  <ItemGroup>
    <Content Include=".gitignore" />
    <Content Include="LICENSE" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="src\Game\" />
  </ItemGroup>
</Project>
